<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/torrent-store.proto

namespace Webtor\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The check request message containing the infoHash
 *
 * Generated from protobuf message <code>webtor.grpc.CheckRequest</code>
 */
class CheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     */
    private $infoHash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $infoHash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TorrentStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     * @return string
     */
    public function getInfoHash()
    {
        return $this->infoHash;
    }

    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInfoHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->infoHash = $var;

        return $this;
    }

}

