<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/torrent-store.proto

namespace Webtor\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The check response message containing existance flag
 *
 * Generated from protobuf message <code>webtor.grpc.CheckReply</code>
 */
class CheckReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     */
    private $exists = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $exists
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TorrentStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     * @return bool
     */
    public function getExists()
    {
        return $this->exists;
    }

    /**
     * Generated from protobuf field <code>bool exists = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setExists($var)
    {
        GPBUtil::checkBool($var);
        $this->exists = $var;

        return $this;
    }

}

