<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/torrent-store.proto

namespace Webtor\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The pull response message containing the torrent
 *
 * Generated from protobuf message <code>webtor.grpc.PullReply</code>
 */
class PullReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes torrent = 1;</code>
     */
    private $torrent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $torrent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TorrentStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes torrent = 1;</code>
     * @return string
     */
    public function getTorrent()
    {
        return $this->torrent;
    }

    /**
     * Generated from protobuf field <code>bytes torrent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTorrent($var)
    {
        GPBUtil::checkString($var, False);
        $this->torrent = $var;

        return $this;
    }

}

