<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/torrent-store.proto

namespace Webtor\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The touch request message containing the torrent and expire duration is seconds
 *
 * Generated from protobuf message <code>webtor.grpc.TouchRequest</code>
 */
class TouchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     */
    private $infoHash = '';
    /**
     * Generated from protobuf field <code>int32 expire = 2;</code>
     */
    private $expire = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $infoHash
     *     @type int $expire
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TorrentStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     * @return string
     */
    public function getInfoHash()
    {
        return $this->infoHash;
    }

    /**
     * Generated from protobuf field <code>string infoHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInfoHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->infoHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expire = 2;</code>
     * @return int
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     * Generated from protobuf field <code>int32 expire = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkInt32($var);
        $this->expire = $var;

        return $this;
    }

}

