<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/torrent-store.proto

namespace Webtor\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The touch response message
 *
 * Generated from protobuf message <code>webtor.grpc.TouchReply</code>
 */
class TouchReply extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\TorrentStore::initOnce();
        parent::__construct($data);
    }

}

